spring.application.name=ServiceFinder

spring.datasource.url=jdbc:mysql://localhost:3306/service_finder
spring.datasource.username=root
spring.datasource.password=Vishnu@21
spring.jpa.hibernate.ddl-auto=update

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437